# Generated by Django 5.0.2 on 2024-09-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='complement',
            new_name='complemento',
        ),
    ]
