# Generated by Django 4.2.6 on 2023-12-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qtt',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
