# Generated by Django 5.0.2 on 2024-08-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_ordemitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
