# Generated by Django 4.2.6 on 2023-12-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_qtt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='stats',
        ),
    ]
