# Generated by Django 4.2.6 on 2023-12-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_status_order_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stats',
            new_name='status',
        ),
    ]
