# Generated by Django 5.0.2 on 2024-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_merchant_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='pix_qrcodes/'),
        ),
    ]
